### ISSUE TITLE
Linking NORA in google home still points to the old app

### ISSUE THREAD

**Issue by Wireheadbe** [andrei-tatar/node-red-contrib-nora-firebase#1]
.. Or do I need to be added somewhere to test the new implementation ;)

**Comment by andrei-tatar** [comment]
Hey, thanks for the interest!

Yes, there will be a new app in the list. I did consider migration, but the old architecture makes it pretty hard to do.
It's not yet visible or open to public testing (I did notice you created an account already :) ).

I'm working on adding local execution and probably a few new features and after that I will open it to beta testing.

**Comment by Wireheadbe** [comment]
Yeah, better to start with a clean slate I guess.. I've just registered indeed. If you need me to test things, drop me a line ;) 
I have one device already in there, in the new implementation.. So if you need to test, fire away :) it's just a light.. 👍🏻

**Comment by chirag828049** [comment]
@andrei-tatar . Currently I am working in a small project related to home automation. I would love to try out . Can you please add me to the discord server ?

**Comment by andrei-tatar** [comment]
I ended up creating a slack channel for chat. 

Here's the invite:
https://join.slack.com/t/smart-nora/shared_invite/zt-m1vy0jfq-j7JrN85waaqw~l8LY5naSg

**Comment by lekv** [comment]
Hi @andrei-tatar, it looks like the Slack invite has expired. Do you mind creating a new invite? Thanks :)

**Comment by Raainman** [comment]
I also would like to join Slack. please create a invite.

**Comment by andrei-tatar** [comment]
https://join.slack.com/t/smart-nora/shared_invite/zt-nn2w4efp-AXE5jUimp8gzqFI9NK62Ng
